## This is the new function to generate the table. This uses the newly downloaded
## data for gbif and idigbio. that is in June 2022

## for comparing the lat-long values for gbifid's from old data to new data
## here basically trying to replace the latlong from georef data given by john
## if the gbif id is found. 

library(readr)

## From desktop 
folderTag = "Z:/"

## For moose
## folderTag = "/srv/"

## Open georef_data - This is new data generated by John
## Z:\mybook\narayani\monocot_pd\WCVP\DownloadedData\spfiles_WCVP

## belsData = read.csv(paste(folderTag, "mybook/narayani/monocot_pd/WCVP/DownloadedData/spfiles_WCVP/Achnatherum_calamagrostis.csv",
##                    sep = ""))
## rawData = read.csv(paste(folderTag, "mybook/narayani/monocot_pd/WCVP/GlobalDownloadedData/spfiles_WCVP/Achnatherum_calamagrostis.csv",
##                         sep = ""))



belsFolder = paste(folderTag, "mybook/narayani/monocot_pd/WCVP/DownloadedData/spfiles_WCVP/",
                   sep = "")
rawFolder = paste(folderTag, "mybook/narayani/monocot_pd/WCVP/GlobalDownloadedData/spfiles_WCVP/", sep = "")

opFolder = paste(folderTag, "mybook/narayani/monocot_pd/WCVP/GlobalDownloadedData/spfiles_WCVP_bels/", sep = "")

allFiles = list.files(rawFolder, pattern = ".csv$", full.names =TRUE)
## allFiles = allFiles[1:10]

for (curFile in allFiles)
{
  
  rawData = read_csv(curFile)
  
  flName = basename(curFile)
  belsFile = paste(belsFolder, flName, sep = "")
  print(paste("Current file ", flName, sep = ""))
  if (file.exists(belsFile))
  {
    print("Bels exists")
    belsData = read_csv(belsFile)
    belsGBIF = belsData$gbifID
    rawGBIF = rawData$gbifID
    
    ## Get matching rawGBIFID in bels. 
    
    rawData$bels_decimallatitude = belsData$bels_decimallatitude[match(rawData$gbifID, belsData$gbifID)]    
    rawData$bels_decimallongitude = belsData$bels_decimallongitude[match(rawData$gbifID, belsData$gbifID)]    

    ##l1 = match(rawData$gbifID, belsData$gbifID)
    ##d1 = which(rawGBIF %in% belsGBIF)
    ##d2 = which(belsGBIF %in% rawGBIF)
  } else {
    
    bels_decimallatitude = rep(NA, nrow(rawData))
    bels_decimallongitude = rep(NA, nrow(rawData))
    rawData = cbind(rawData, bels_decimallongitude, bels_decimallatitude)
    
  }
    
    

  
  idNAs = which((is.na(rawData$decimalLatitude) == TRUE) 
                & is.na(rawData$bels_decimallatitude) == TRUE)
  if (length(idNAs) > 0 )
  {
    rawData1 = rawData[-idNAs, ]
  }
  
  opFile = paste(opFolder, flName, sep = "")
  
  write.csv(rawData1, opFile, row.names = FALSE)
  
  
  
} ## for






# Make table to generate how many species with how many records. 

library(readr)
#DataFolder <- "./spfiles_WCVP/"

DataFolder <- paste(folderTag, "mybook/narayani/monocot_pd/WCVP/GlobalDownloadedData/spfiles_WCVP_bels/", sep = "")


Files <- list.files(DataFolder, pattern = ".csv$", full.names = TRUE)
print(length(Files))


OpMat <- matrix(0, ncol = 5, nrow = length(Files))
spcount <- 1
for (curfile in Files)
{
  
  dt1 <- read_csv(curfile)
  spname <- dt1$canonical[1]
  TotRecords <- nrow(dt1)

  if (TotRecords > 0 )
  {
  ## Raw latitude and longitude
  decll = which(dt1$decimalLatitude > 0 & dt1$decimalLongitude > 0
                | !is.na(dt1$decimalLatitude))
  
  belsll = which(dt1$bels_decimallatitude > 0 & dt1$bels_decimallongitude > 0
                | !is.na(dt1$bels_decimallatitude))
  
  comb_ll = unique(c(decll, belsll))
  
  OpMat[spcount, 1] <- as.character(spname)
  OpMat[spcount, 2] <- TotRecords
  OpMat[spcount, 3] <- length(decll)
  OpMat[spcount, 4] <- length(belsll)
  OpMat[spcount, 5] <- length(comb_ll)
  
  } else
    
  {
    
    OpMat[spcount, 1] <- as.character(spname)
  }
  #tt3 = dt1[-decll, c("canonical", "decimalLatitude", "decimalLongitude", "bels_decimallatitude", "bels_decimallongitude")]

  spcount = spcount + 1
  print(spcount)
  print(curfile)
  
  
}

OpMat1 = data.frame(OpMat)
names(OpMat1) = c("SpName", "TotalRec", "gbif_LL", "bels_ll", "Tot_ll")

## write.csv(OpMat1, "./results/SpCount_WCVP.csv", row.names = FALSE)


## Generate the table to know how many speices have how many occurrences.
SpMat1 = read.csv("./results/SpCount_WCVP.csv")

## Remove values with NA
if (length(which(is.na(SpMat1[,1]) == TRUE)) > 0 )
{
  SpMat = SpMat1[!is.na(SpMat1[,1]),]
}
tbl1 = matrix(0,nrow=0,ncol=5)

## count species with value 1
cnt1_rec = length(which(SpMat[,2] ==  1 ))
cnt1_georec = length(which(SpMat[,4] ==  1 ))
cnt1_totrec = length(which(SpMat[,5] ==  1 ))
NewRow = c(1, 1, cnt1_rec, cnt1_georec, cnt1_totrec)
tbl1 = rbind(tbl1, NewRow)

## count speices with value less than 10 
cnt10_rec = length(which(SpMat[,2] >  1  & SpMat[,2] <=  10))
cnt10_georec = length(which(SpMat[,4] >  1  & SpMat[,4] <=  10))
cnt10_totrec = length(which(SpMat[,5] >  1  & SpMat[,5] <=  10))
NewRow = c(2, 10, cnt10_rec, cnt10_georec,cnt10_totrec)
tbl1 = rbind(tbl1, NewRow)


## count speices with value 
cnt50_rec = length(which(SpMat[,2] >  10  & SpMat[,2] <=  50))
cnt50_georec = length(which(SpMat[,4] >  10  & SpMat[,4] <=  50))
cnt50_totrec = length(which(SpMat[,5] >  10  & SpMat[,5] <=  50))
NewRow = c(11, 50, cnt50_rec, cnt50_georec, cnt50_totrec)
tbl1 = rbind(tbl1, NewRow)


## count speices with value 
cnt100_rec = length(which(SpMat[,2] >  50  & SpMat[,2] <=  100))
cnt100_georec = length(which(SpMat[,4] >  50  & SpMat[,4] <=  100))
cnt100_totrec = length(which(SpMat[,5] >  50  & SpMat[,5] <=  100))
NewRow = c(51, 100, cnt100_rec, cnt100_georec, cnt100_totrec)
tbl1 = rbind(tbl1, NewRow)


## count speices with value 
cnt500_rec = length(which(SpMat[,2] >  100  & SpMat[,2] <=  500))
cnt500_georec = length(which(SpMat[,4] >  100  & SpMat[,4] <=  500))
cnt500_totrec = length(which(SpMat[,5] >  100  & SpMat[,5] <=  500))
NewRow = c(101, 500, cnt500_rec, cnt500_georec, cnt500_totrec)
tbl1 = rbind(tbl1, NewRow)


## count speices with value 
cnt1000_rec = length(which(SpMat[,2] >  500  & SpMat[,2] <=  1000))
cnt1000_georec = length(which(SpMat[,4] >  500  & SpMat[,4] <=  1000))
cnt1000_totrec = length(which(SpMat[,5] >  500  & SpMat[,5] <=  1000))
NewRow = c(501, 1000, cnt1000_rec, cnt1000_georec, cnt1000_totrec)
tbl1 = rbind(tbl1, NewRow)


## count speices with value 
cnt1000_rec = length(which(SpMat[,2] >  1000))
cnt1000_georec = length(which(SpMat[,4] >  1000))
cnt1000_totrec = length(which(SpMat[,5] >  1000))
NewRow = c(1001, 133125, cnt1000_rec, cnt1000_georec, cnt1000_totrec)

tbl1 = rbind(tbl1, NewRow)
tbl2 = data.frame(tbl1)
names(tbl2) = c("From", "To", "raw_ll", "geo_ll", "tot_ll")

write.csv(tbl2, "./results/OccBinTable_WCVP.csv", row.names = FALSE)


